import { createServer, type Server } from 'node:http';
import type { AddressInfo } from 'node:net';
import { mkdtemp, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { parse } from 'yaml';
import { parseConfig } from '../../src/config/config-loader.js';
import type { ExplorationResult } from '../../src/model/exploration-result.js';
import { runMission } from '../../src/orchestrator.js';

const PAGES: Record<string, string> = {
  '/': '<h1>Dashboard</h1><nav><a href="/users">Users</a> <a href="/settings">Settings</a></nav>',
  '/users': `<h1>Users</h1><a href="/users/new">Create user</a>
    <button onclick="document.getElementById('d').hidden = false">Details</button>
    <div id="d" role="dialog" aria-label="User details" hidden><h2>User details</h2><p>Alice</p></div>`,
  '/users/new': `<h1>Create user</h1><form onsubmit="event.preventDefault()">
    <label for="first">First name</label><input id="first" required>
    <label for="mail">Email</label><input id="mail" type="email" required>
    <label for="role">Role</label><select id="role"><option value="">-- Choose --</option><option>Reader</option><option>Editor</option></select>
    <label for="secret">Password</label><input id="secret" type="password">
    <button type="submit">Save</button></form>`,
  '/settings': `<h1>Settings</h1>
    <div role="tablist"><button role="tab" aria-selected="true" id="t1" onclick="select(1)">General</button>
      <button role="tab" aria-selected="false" id="t2" onclick="select(2)">Security</button></div>
    <section id="p1"><h2>General settings</h2></section><section id="p2" hidden><h2>Security settings</h2></section>
    <script>function select(n) { [1, 2].forEach((i) => { document.getElementById('t' + i).setAttribute('aria-selected', String(i === n)); document.getElementById('p' + i).hidden = i !== n; }); }</script>`,
};

describe('flows generated from the exploration', () => {
  let server: Server;
  let url = '';
  let outputDir = '';
  let explored: ExplorationResult;
  let yamlText = '';

  const mission = (name: string, extra: string, autonomous = true): string => `
mission: { name: ${name} }
target: { baseUrl: ${url} }
exploration: { maxStates: 20, maxActions: 40, actionTimeoutMs: 2000, settleTimeMs: 50, autonomous: ${String(autonomous)} }
output:
  reportsDir: ${path.join(outputDir, name)}
  screenshotsDir: ${path.join(outputDir, name, 'shots')}
${extra}`;

  beforeAll(async () => {
    server = createServer((req, res) => {
      const body = PAGES[req.url ?? ''];
      res.writeHead(body ? 200 : 404, { 'content-type': 'text/html; charset=utf-8' });
      res.end(
        `<!doctype html><html><head><meta charset="utf-8"><title>App</title></head><body>${body ?? 'Not found'}</body></html>`,
      );
    });
    await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
    url = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
    outputDir = await mkdtemp(path.join(tmpdir(), 'qa-flowgen-'));
    explored = (await runMission(parseConfig(mission('explore', ''), {}, {}).config)).result;
    yamlText = await readFile(explored.artifacts.generatedFlows ?? '', 'utf8');
  });
  afterAll(async () => {
    await new Promise((resolve) => server.close(resolve));
  });

  it('writes one flow per screen at the end of a path', () => {
    const { flows } = parse(yamlText) as { flows: { name: string; steps: Record<string, unknown>[] }[] };
    const names = flows.map((flow) => flow.name).sort();
    expect(names).toEqual(
      expect.arrayContaining(['to-create-user', 'to-users-user-details', 'to-settings-security']),
    );
    // Les écrans intermédiaires (Users) sont couverts par les flows qui y passent.
    expect(names).not.toContain('to-users');
    expect(yamlText.startsWith('# Flows generated by QA-CRAWLER')).toBe(true);
  });

  it('replays the forms with the values used; a sensitive field reads an environment variable', () => {
    const { flows } = parse(yamlText) as { flows: { name: string; steps: Record<string, unknown>[] }[] };
    const create = flows.find((flow) => flow.name === 'to-create-user');
    expect(create?.steps).toEqual(
      expect.arrayContaining([
        { click: { role: 'link', name: 'Users', exact: true } },
        { click: { role: 'link', name: 'Create user', exact: true } },
        {
          fill: {
            role: 'textbox',
            name: 'Email',
            exact: true,
            value: expect.stringMatching(/@example\.test$/) as unknown as string,
          },
        },
        { select: { role: 'combobox', name: 'Role', exact: true, option: 'Reader' } },
        { name: 'on create-user', expect: { text: 'Create user' } },
      ]),
    );
    // Le champ mot de passe est laissé hors du plan : aucune valeur, et aucun secret dans le fichier.
    expect(yamlText).not.toMatch(/Password[\s\S]{0,40}value: (?!\{)/);
  });

  it('the generated flows run and pass as an imposed mission', async () => {
    const flows = yamlText.replace(/^#.*\n/gm, '');
    const replay = parseConfig(mission('replay', flows, false), {}, {}).config;
    expect(replay.flows.length).toBeGreaterThanOrEqual(3);
    const { result } = await runMission(replay);
    const statuses = Object.fromEntries(result.flows.map((flow) => [flow.name, flow.status]));
    expect(
      Object.values(statuses).every((status) => status === 'PASSED'),
      JSON.stringify(statuses),
    ).toBe(true);
  });
});
