/**
 * Languages of the HTML reports. result.json and flow-graph.json always stay
 * in English (stable keys and values for tools and CI).
 */
export const REPORT_LANGUAGES = ['en', 'fr'] as const;
export type ReportLanguage = (typeof REPORT_LANGUAGES)[number];

export interface ReportTexts {
  lang: ReportLanguage;
  reportTitle: string;
  stopped: string;
  engine: string;
  flowGraphLink: string;
  backToReport: string;
  status: { critical: string; errors: string; warnings: string; none: string };
  cards: {
    states: string;
    transitions: string;
    actionsExecuted: string;
    actionsBlocked: string;
    blocked: string;
    failed: string;
    maxDepth: string;
    backtracks: string;
    issues: string;
    flowsPassed: string;
    duration: string;
  };
  discoveredFlow: string;
  discoveredFlowHint: string;
  issueSections: { flow: string; http: string; js: string; navigation: string };
  noneDetected: string;
  columns: {
    severity: string;
    status: string;
    request: string;
    message: string;
    stateActionFlow: string;
    count: string;
    shot: string;
    state: string;
    urlRoute: string;
    depth: string;
    actions: string;
    forms: string;
    issues: string;
    class: string;
    type: string;
    category: string;
    label: string;
    locator: string;
    reason: string;
    from: string;
    action: string;
    to: string;
    result: string;
    duration: string;
    step: string;
  };
  after: string;
  view: string;
  noLabel: string;
  sameState: string;
  optional: string;
  actionCount: (count: number) => string;
  issueCount: (count: number) => string;
  statesTitle: string;
  noState: string;
  executedTitle: string;
  noExecuted: string;
  blockedTitle: string;
  blockedHint: string;
  noBlocked: string;
  screenshotsTitle: string;
  noScreenshots: string;
  generatedBy: string;
  flowsTitle: string;
  flowsHint: string;
  lastScreenExplored: string;
  flowGraphTitle: string;
  applicationMap: string;
  textView: string;
  movesTitle: string;
  othersTitle: string;
  othersHint: string;
}

const EN: ReportTexts = {
  lang: 'en',
  reportTitle: 'QA Flow Explorer',
  stopped: 'stopped',
  engine: 'engine',
  flowGraphLink: 'Flow graph →',
  backToReport: '← Report',
  status: {
    critical: 'CRITICAL issues found',
    errors: 'Errors found',
    warnings: 'Warnings only',
    none: 'No issues',
  },
  cards: {
    states: 'States',
    transitions: 'Transitions',
    actionsExecuted: 'Actions executed',
    actionsBlocked: 'Actions blocked',
    blocked: 'Blocked',
    failed: 'Failed',
    maxDepth: 'Max depth',
    backtracks: 'Backtracks',
    issues: 'Issues',
    flowsPassed: 'Flows passed',
    duration: 'Duration',
  },
  discoveredFlow: 'Discovered flow',
  discoveredFlowHint:
    'Each state appears under the state from which it was first reached, with the action that led there.',
  issueSections: {
    flow: 'Flow failures',
    http: 'HTTP errors & broken pages',
    js: 'JavaScript errors',
    navigation: 'Navigation problems',
  },
  noneDetected: 'None detected.',
  columns: {
    severity: 'Severity',
    status: 'Status',
    request: 'Request',
    message: 'Message',
    stateActionFlow: 'State · action · flow',
    count: 'Count',
    shot: 'Shot',
    state: 'State',
    urlRoute: 'URL · route',
    depth: 'Depth',
    actions: 'Actions',
    forms: 'Forms',
    issues: 'Issues',
    class: 'Class',
    type: 'Type',
    category: 'Category',
    label: 'Label',
    locator: 'Locator',
    reason: 'Reason',
    from: 'From',
    action: 'Action',
    to: 'To',
    result: 'Result',
    duration: 'Duration',
    step: 'Step',
  },
  after: 'after',
  view: 'view',
  noLabel: '(no label)',
  sameState: '(same state)',
  optional: '(optional)',
  actionCount: (count) => `${count} action(s)`,
  issueCount: (count) => `${count} issue(s)`,
  statesTitle: 'States',
  noState: 'No state discovered.',
  executedTitle: 'Executed actions',
  noExecuted: 'No action executed.',
  blockedTitle: 'Blocked actions',
  blockedHint: 'Refused by the safety policy (after the decision engine chose them, before Playwright).',
  noBlocked: 'No action was blocked.',
  screenshotsTitle: 'Screenshots',
  noScreenshots: 'No screenshots were captured.',
  generatedBy: 'Generated by qa-crawler (flow explorer)',
  flowsTitle: 'Imposed flows',
  flowsHint:
    'Steps written in the mission, run in order. Each step still goes through the safety policy: DANGEROUS actions never run, MUTATION ones only with <code>allow: MUTATION</code>.',
  lastScreenExplored: 'last screen explored',
  flowGraphTitle: 'Flow graph',
  applicationMap: 'Application map',
  textView: 'Text view',
  movesTitle: 'Transitions between states',
  othersTitle: 'Other attempts',
  othersHint: 'Actions without visible effect, failed or blocked by the safety policy.',
};

const FR: ReportTexts = {
  lang: 'fr',
  reportTitle: 'Rapport QA',
  stopped: 'arrêt',
  engine: 'moteur',
  flowGraphLink: 'Graphe des flows →',
  backToReport: '← Rapport',
  status: {
    critical: 'Anomalies CRITIQUES',
    errors: 'Erreurs détectées',
    warnings: 'Avertissements seulement',
    none: 'Aucune anomalie',
  },
  cards: {
    states: 'États',
    transitions: 'Transitions',
    actionsExecuted: 'Actions exécutées',
    actionsBlocked: 'Actions bloquées',
    blocked: 'Bloquées',
    failed: 'Échouées',
    maxDepth: 'Profondeur max',
    backtracks: 'Retours arrière',
    issues: 'Anomalies',
    flowsPassed: 'Flows réussis',
    duration: 'Durée',
  },
  discoveredFlow: 'Parcours découvert',
  discoveredFlowHint:
    "Chaque état apparaît sous l'état depuis lequel il a été atteint la première fois, avec l'action qui y a mené.",
  issueSections: {
    flow: 'Échecs des flows',
    http: 'Erreurs HTTP et pages cassées',
    js: 'Erreurs JavaScript',
    navigation: 'Problèmes de navigation',
  },
  noneDetected: 'Aucune détectée.',
  columns: {
    severity: 'Gravité',
    status: 'Statut',
    request: 'Requête',
    message: 'Message',
    stateActionFlow: 'État · action · parcours',
    count: 'Nb',
    shot: 'Capture',
    state: 'État',
    urlRoute: 'URL · route',
    depth: 'Profondeur',
    actions: 'Actions',
    forms: 'Formulaires',
    issues: 'Anomalies',
    class: 'Classe',
    type: 'Type',
    category: 'Catégorie',
    label: 'Libellé',
    locator: 'Localisateur',
    reason: 'Raison',
    from: 'Depuis',
    action: 'Action',
    to: 'Vers',
    result: 'Résultat',
    duration: 'Durée',
    step: 'Étape',
  },
  after: 'après',
  view: 'voir',
  noLabel: '(sans libellé)',
  sameState: '(même état)',
  optional: '(optionnelle)',
  actionCount: (count) => `${count} action(s)`,
  issueCount: (count) => `${count} anomalie(s)`,
  statesTitle: 'États',
  noState: 'Aucun état découvert.',
  executedTitle: 'Actions exécutées',
  noExecuted: 'Aucune action exécutée.',
  blockedTitle: 'Actions bloquées',
  blockedHint:
    'Refusées par la politique de sécurité (après le choix du moteur de décision, avant Playwright).',
  noBlocked: "Aucune action n'a été bloquée.",
  screenshotsTitle: "Captures d'écran",
  noScreenshots: "Aucune capture d'écran.",
  generatedBy: 'Généré par qa-crawler (explorateur de flows)',
  flowsTitle: 'Flows imposés',
  flowsHint:
    'Étapes écrites dans la mission, exécutées dans l’ordre. Chaque étape passe par la politique de sécurité : les actions DANGEREUSES ne sont jamais exécutées, les MODIFICATIONS seulement avec <code>allow: MUTATION</code>.',
  lastScreenExplored: 'dernier écran exploré',
  flowGraphTitle: 'Graphe des flows',
  applicationMap: "Carte de l'application",
  textView: 'Vue texte',
  movesTitle: 'Transitions entre états',
  othersTitle: 'Autres tentatives',
  othersHint: 'Actions sans effet visible, échouées ou bloquées par la politique de sécurité.',
};

export function reportTexts(language: ReportLanguage = 'en'): ReportTexts {
  return language === 'fr' ? FR : EN;
}

/** French labels of the enum values shown in the reports (statuses, classes, severities…). */
const FR_VALUES: Record<string, string> = {
  // flow and transition results
  PASSED: 'RÉUSSI',
  FAILED: 'ÉCHOUÉ',
  BLOCKED: 'BLOQUÉ',
  SKIPPED: 'IGNORÉ',
  SUCCESS: 'RÉUSSIE',
  // classifications
  SAFE: 'SÛRE',
  MUTATION: 'MODIFICATION',
  DANGEROUS: 'DANGEREUSE',
  UNKNOWN: 'INCONNUE',
  // severities
  INFO: 'INFO',
  WARNING: 'AVERTISSEMENT',
  ERROR: 'ERREUR',
  CRITICAL: 'CRITIQUE',
  // issue types
  HTTP: 'HTTP',
  REQUEST_FAILED: 'REQUÊTE ÉCHOUÉE',
  BROKEN_LINK: 'LIEN CASSÉ',
  CONSOLE: 'CONSOLE',
  PAGE_ERROR: 'ERREUR JS',
  PAGE_CRASH: 'PLANTAGE',
  NAVIGATION: 'NAVIGATION',
  FLOW: 'FLOW',
  // action types
  click: 'clic',
  navigate: 'navigation',
  fill: 'saisie',
  select: 'sélection',
  check: 'cocher',
  uncheck: 'décocher',
  // step kinds
  goto: 'aller à',
  expect: 'vérification',
  screenshot: 'capture',
  // categories
  navigation: 'navigation',
  tab: 'onglet',
  menu: 'menu',
  details: 'détails',
  pagination: 'pagination',
  search: 'recherche',
  filter: 'filtre',
  'form-input': 'champ',
  'form-step': 'étape de formulaire',
  submit: 'envoi',
  toggle: 'bascule',
  other: 'autre',
  // stop reasons
  exhausted: 'tout exploré',
  'flows-only': 'flows uniquement',
  'max-states': 'nombre max d’états atteint',
  'max-actions': 'nombre max d’actions atteint',
  'max-duration': 'durée max atteinte',
  'engine-stop': 'arrêt du moteur',
  'unreachable-start': 'page de départ inaccessible',
  'rule-based': 'à règles',
};

/** Display label of an enum value (status, class, severity, action type…). */
export function valueLabel(language: ReportLanguage, value: string): string {
  return language === 'fr' ? (FR_VALUES[value] ?? value) : value;
}

/**
 * French wording of the reasons produced by the SafetyPolicy, the flow
 * runner and the explorer. Applied on the whole text, so nested reasons
 * ("MUTATION action (matches mutation keyword "x"): …") are translated too.
 * Unknown text (browser messages…) is left as is.
 */
const FR_REASONS: [RegExp, string | ((...groups: string[]) => string)][] = [
  [
    /Flow "(.*?)" — step (\d+) "(.*)" (failed|blocked): /g,
    (_match, flow = '', step = '', description = '', status = '') =>
      `Flow « ${flow} » — étape ${step} « ${description} » ${status === 'failed' ? 'échouée' : 'bloquée'} : `,
  ],
  [/Flow "(.*?)" — could not start: /g, 'Flow « $1 » — démarrage impossible : '],
  [
    /:? add "allow: (MUTATION|UNKNOWN)" to this step to execute it/g,
    ' : ajoutez « allow: $1 » à cette étape pour l’exécuter',
  ],
  [/MUTATION action \(/g, 'action de MODIFICATION ('],
  [/UNKNOWN action \(/g, 'action INCONNUE ('],
  [/DANGEROUS actions are never executed/g, 'les actions DANGEREUSES ne sont jamais exécutées'],
  [/DANGEROUS URL is never opened/g, 'une URL DANGEREUSE n’est jamais ouverte'],
  [
    /(SAFE|MUTATION|DANGEROUS|UNKNOWN) actions are not allowed/g,
    (_match, cls = '') => `les actions ${valueLabel('fr', cls)} ne sont pas autorisées`,
  ],
  [/URL matches dangerous keyword "(.*?)"/g, 'l’URL contient le mot-clé dangereux « $1 »'],
  [/matches dangerous keyword "(.*?)"/g, 'mot-clé dangereux « $1 »'],
  [/matches mutation keyword "(.*?)"/g, 'mot-clé de modification « $1 »'],
  [/risk "(.*?)" is blocked by the mission/g, 'le risque « $1 » est bloqué par la mission'],
  [/the mission does not allow "(.*?)" actions/g, 'la mission n’autorise pas les actions « $1 »'],
  [/navigation refused: /g, 'navigation refusée : '],
  [/\bexternal-host\b/g, 'hôte externe'],
  [/\bignored-path\b/g, 'chemin ignoré'],
  [/\bdangerous-url\b/g, 'URL dangereuse'],
  [/\bnon-html-resource\b/g, 'fichier, pas une page'],
  [/\bunsupported-scheme\b/g, 'protocole non pris en charge'],
  [/submits a search form/g, 'envoie un formulaire de recherche'],
  [/submits a form/g, 'envoie un formulaire'],
  [
    /sensitive field \(password, payment or secret data\): never filled/g,
    'champ sensible (mot de passe, paiement ou secret) : jamais rempli',
  ],
  [
    /sensitive field \(password, secret…\): its value must come from an environment variable \(\{ env: NAME \}\)/g,
    'champ sensible (mot de passe, secret…) : la valeur doit venir d’une variable d’environnement ({ env: NOM })',
  ],
  [
    /sensitive field filled from an environment variable \(value never logged\)/g,
    'champ sensible rempli depuis une variable d’environnement (valeur jamais journalisée)',
  ],
  [
    /payment field \(card, IBAN…\): never filled automatically/g,
    'champ de paiement (carte, IBAN…) : jamais rempli automatiquement',
  ],
  [
    /no readable label \(icon or symbol only\): never executed automatically/g,
    'aucun libellé lisible (icône ou symbole seul) : jamais exécuté automatiquement',
  ],
  [/element is disabled/g, 'élément désactivé'],
  [/element is not visible/g, 'élément non visible'],
  [
    /element not visible within (\d+) ms \((\d+) match\(es\)\)/g,
    'élément non visible après $1 ms ($2 correspondance(s))',
  ],
  [/element not found within (\d+) ms/g, 'élément introuvable après $1 ms'],
  [/element not found on the page/g, 'élément introuvable sur la page'],
  [/element still visible/g, 'élément toujours visible'],
  [/expected element: /g, 'élément attendu : '],
  [/environment variable (\S+) is not set/g, 'la variable d’environnement $1 n’est pas définie'],
  [/expectation not met: /g, 'vérification non satisfaite : '],
  [/text "(.*?)" not visible/g, 'texte « $1 » non visible'],
  [/URL does not contain "(.*?)"/g, 'l’URL ne contient pas « $1 »'],
  [/cannot inspect the element: /g, 'impossible d’inspecter l’élément : '],
  [/navigation to (\S+) failed/g, 'échec de la navigation vers $1'],
  [
    /left the allowed hosts(,)? or the page (failed to load|crashed)/g,
    'sortie des hôtes autorisés, ou la page n’a pas chargé',
  ],
  [/\bpage crashed\b/g, 'la page a planté'],
  [/action not available on this state/g, 'action absente de cet état'],
  [/invalid link target/g, 'cible de lien invalide'],
  [/invalid URL/g, 'URL invalide'],
  [
    /\bstep (\d+) (failed|blocked)\b/g,
    (_match, step = '', status = '') => `étape ${step} ${status === 'failed' ? 'échouée' : 'bloquée'}`,
  ],
  [/\bflow stopped\b/g, 'flow arrêté'],
  [/mission limit reached \((.*?)\)/g, 'limite de la mission atteinte ($1)'],
  [/start page (\S+) could not be loaded/g, 'la page de départ $1 n’a pas pu être chargée'],
  [/the start page is unreachable/g, 'la page de départ est inaccessible'],
  [/in-page control \((.*?)\), no risky keyword/g, 'contrôle de la page ($1), aucun mot-clé risqué'],
  [/navigation \(GET, no data change\)/g, 'navigation (GET, aucune modification)'],
  [/link to another site/g, 'lien vers un autre site'],
  [/file download, not a screen/g, 'téléchargement de fichier, pas un écran'],
  [/fills a field locally \(nothing is sent\)/g, 'remplit un champ localement (rien n’est envoyé)'],
  [/wizard step "(.*?)" \(client-side form\)/g, 'étape d’assistant « $1 » (formulaire côté client)'],
  [/\bplain navigation\b/g, 'navigation simple'],
  [/\bnavigation allowed\b/g, 'navigation autorisée'],
];

/** Reason or message in the report language. */
export function translateReason(language: ReportLanguage, text: string): string {
  if (language !== 'fr') return text;
  let result = text;
  for (const [pattern, replacement] of FR_REASONS) {
    result =
      typeof replacement === 'string'
        ? result.replace(pattern, replacement)
        : result.replace(pattern, (...args: unknown[]) =>
            replacement(...args.slice(0, -2).map((value) => (typeof value === 'string' ? value : ''))),
          );
  }
  return result;
}
